Update model training pipeline

diff --git a/.github/workflows/train_and_deploy_v0.1.yml b/.github/workflows/train_and_deploy_v0.1.yml
--- a/.github/workflows/train_and_deploy_v0.1.yml
+++ b/.github/workflows/train_and_deploy_v0.1.yml
@@ -4,6 +4,8 @@ on:
   push: 
     branches:
       - main
+    tags:
+      - 'v*'
 
   pull_request:
     branches:
@@ -39,7 +41,8 @@ jobs:
         run:
           pylint scripts/ --output-format=parseable > pylint-report.txt || true
 
-  build-and-push:
+  train-model:
+    name: Train Model
     runs-on: ubuntu-latest
     needs: lint
 
@@ -64,7 +67,35 @@ jobs:
         name: diabetes-model
         path: models/
     
-    # Docker Hub
+  unit-test:
+    name: Unit testing
+    runs-on: ubuntu-latest
+    needs: train-model
+
+    steps:
+    - name: Checkout repository
+      uses: actions/checkout@v2
+    
+    - name: Set up Python
+      uses: actions/setup-python@v4
+      with:
+        python-version: '3.11'
+      
+    - name: Install dependencies
+      run: |
+        python -m pip install --upgrade pip
+        pip install pytest fastapi[all]
+        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+    
+    - name: Run Unit Test
+      run: pytest -v tests/
+
+  build-container:
+    name: Build Docker image
+    runs-on: ubuntu-latest
+    needs: unit-test
+
+    steps:
 
     - name: Log in to Docker Hub
       uses: docker/login-action@v3
@@ -74,7 +105,35 @@ jobs:
       
     - name: Build Docker image
       run: docker build -t ${{ secrets.DOCKER_USERNAME }}/diabetes_progression:${{ env.VERSION }} .
-    
+  
+  container-smoke-test:
+    name: Container Smoke Test
+    runs-on: ubuntu-latest
+    needs: build-container
+
+    steps:
+      - name: Container Smoke Test
+        run: |
+          docker run -d -p 8080:8080 --name diabetes_app_test ${{ secretes.DOCKER_USERNAME }}/diabetes_progression:${{ env.VERSION }}
+          sleep 5
+          curl -f https://localhost:8080/health || (echo "Smoke test failed" && docker logs diabetes_app_test && exit 1)
+          echo "Smoke test passed"
+          docker rm -f diabetes_app_test
+  
+  deploy-container:
+
+    name: Deploy Container to DockerHub, GHCR
+    runs-on: ubuntu-latest
+    needs: container-smoke-test
+
+    steps:
+
+    #DOCKER HUB
+    - name: Log in to Docker Hub
+      uses: docker/login-action@v3
+      with:
+        username: ${{ secrets.DOCKER_USERNAME }}
+        password: ${{ secrets.DOCKER_PASSWORD }}
     - name: Push Docker image
       run: docker push ${{ secrets.DOCKER_USERNAME }}/diabetes_progression:${{ env.VERSION }}
 
@@ -105,6 +164,12 @@ jobs:
         release_name: Model ${{ env.VERSION }}
         draft: false
         prerelease: false
+      
+    - name: Download model artifact
+      uses: actions/download-artifact@v4
+      with:
+        name: diabetes-model
+        path: ./models/
 
     - name: Upload model artifact to Release
       uses: actions/upload-release-asset@v1
