Update workflows

diff --git a/.github/workflows/train_and_deploy_v0.1.yml b/.github/workflows/train_and_deploy_v0.1.yml
--- a/.github/workflows/train_and_deploy_v0.1.yml
+++ b/.github/workflows/train_and_deploy_v0.1.yml
@@ -5,7 +5,7 @@ on:
     branches:
       - main
     tags:
-      - 'v*'
+      - 'v0.1*'
 
   pull_request:
     branches:
@@ -14,7 +14,7 @@ on:
   workflow_dispatch:
 
 env:
-  VERSION: v0.1.10
+  VERSION: v0.1.11
 
 jobs:
 
@@ -90,10 +90,10 @@ jobs:
     - name: Run Unit Test
       run: pytest -v tests/
 
-  build-container:
-    name: Build Docker image
+  container-smoke-test:
+    name: Container Smoke Test
     runs-on: ubuntu-latest
-    needs: unit-test
+    needs: build-container
 
     steps:
 
@@ -108,20 +108,14 @@ jobs:
       
     - name: Build Docker image
       run: docker build -t ${{ secrets.DOCKER_USERNAME }}/diabetes_progression:${{ env.VERSION }} .
-  
-  container-smoke-test:
-    name: Container Smoke Test
-    runs-on: ubuntu-latest
-    needs: build-container
-
-    steps:
-      - name: Container Smoke Test
-        run: |
-          docker run -d -p 8386:8386 --name diabetes_app_test ${{ secrets.DOCKER_USERNAME }}/diabetes_progression:${{ env.VERSION }}
-          sleep 5
-          curl -f http://localhost:8386/health || (echo "Smoke test failed" && docker logs diabetes_app_test && exit 1)
-          echo "Smoke test passed"
-          docker rm -f diabetes_app_test
+    
+    - name: Container Smoke Test
+      run: |
+        docker run -d -p 8386:8386 --name diabetes_app_test ${{ secrets.DOCKER_USERNAME }}/diabetes_progression:${{ env.VERSION }}
+        sleep 5
+        curl -f http://localhost:8386/health || (echo "Smoke test failed" && docker logs diabetes_app_test && exit 1)
+        echo "Smoke test passed"
+        docker rm -f diabetes_app_test
   
   deploy-container:
 
